#!/bin/sh

case "$0" in
    /*) script_path="$0" ;;
    *) script_path="$PWD/$0" ;;
esac
# Without realpath, running ./10j from the cli/ directory
# would result in script_path ending with "cli/./10j",
# tenjdir ending with "cli/." and rootdir ending up
# as the cli dir.
realscr=$(realpath "$script_path")
tenjdir=$(dirname "$realscr")
rootdir=$(dirname "$tenjdir")

localuv="${rootdir}/_local/uv"
localcg="${rootdir}/_local/uv.toml"

if [ ! -e "$localuv" ] || [ ! -e "$localcg" ]; then
    sh "$tenjdir/sh/provision.sh" uv

    if [ "$1" = "" ]; then
        echo 'Please run `10j provision` to continue setup.'
        exit 0
    fi
fi

# If/when we want to update the uv binary, we should do that here.

if [ -e "$localuv" ] && [ -e "$localcg" ]; then
    exec "$localuv" run --project "$tenjdir" --config-file "$localcg" "$tenjdir/main.py" "$@"
else
    echo "10j's provisioning failed -- sorry!" >&2
    exit 1
fi
